name: Scrape Tweets

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Clean Python environment
        run: |
          sudo rm -rf ~/.cache/pip
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run scraper
        run: python scrape.py

      - name: Commit new data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add tweets.jsonl screenshots/
          git commit -m "🤖 Auto-update tweet data" || echo "No changes to commit"
          git push
