name: Scrape Tweets

on:
  workflow_dispatch:

jobs:
  scrape:
    name: Test snscrape on 22.04
    runs-on: [self-hosted, linux, X64]

    steps:
      - name: Force Ubuntu 22.04 image
        run: |
          echo "This workflow should run on self-hosted runner, not ubuntu-24.04"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install snscrape
        run: pip install snscrape

      - name: Test scraping
        run: |
          python -c "import snscrape.modules.twitter as sntwitter; tweets = list(sntwitter.TwitterUserScraper('kanyewest').get_items()); print(f'Found {len(tweets[:5])} tweets')"
